import io
import openpyxl
import streamlit as st
import processors.dm_stats_processor as dm_stats

st.set_page_config(
    page_title="DM Stats",
    page_icon="📊",
    layout="wide"
)

st.title("📊 DEMOGRAFIK Generator")

uploaded_files = st.file_uploader(
    "Upload Excel file(s)",
    type=["xlsx", "xls"],
    accept_multiple_files=True,
    key="dm_stats_excel_uploader"
)

st.subheader("Age Group Configuration")

age_group_text = st.text_input(
    "Age groups",
    value="18-21, 22-30, 31-40, 41-50, 51-60, 61+",
    help="Enter age groups separated by commas. Example: 18-24, 25-30, 31-40, 41-50, 51-60, 61+"
)

age_groups = dm_stats.parse_age_groups(age_group_text)

if age_groups:
    st.caption("Active age groups: " + " | ".join(age_groups))
else:
    st.error("Invalid age group configuration. Example: 18-21, 22-30, 31-40, 41-50, 51-60, 61+")


def apply_number_formatting(excel_bytes):
    """
    Apply consistent number formatting to every table in the generated workbook.

    Count columns:
        #,##0

    Percentage columns:
        0.0"%"

    The percentage values generated by dm_stats_processor are already stored
    as values such as 18.5, so 0.0"%" is used instead of Excel's 0.0% format.
    """
    input_buffer = io.BytesIO(excel_bytes)
    wb = openpyxl.load_workbook(input_buffer)

    for ws in wb.worksheets:
        # Main table: identify percentage columns from the header row.
        if ws.max_row >= 1:
            header_map = {
                col: ws.cell(1, col).value
                for col in range(1, ws.max_column + 1)
            }

            for col, header in header_map.items():
                if header is None:
                    continue

                is_percentage = '(%)' in str(header)

                for row in range(2, ws.max_row + 1):
                    cell = ws.cell(row, col)
                    if isinstance(cell.value, (int, float)):
                        cell.number_format = '0.0"%"' if is_percentage else '#,##0'

        # Secondary DUN age/race/gender tables.
        # Their first row is a merged title, followed by race headers and
        # gender rows. Percentage columns are every second column after A.
        for row in range(1, ws.max_row + 1):
            first_value = ws.cell(row, 1).value
            if not isinstance(first_value, str):
                continue

            if 'UMUR MENGIKUT KAUM DAN JANTINA' not in first_value.upper():
                continue

            # Locate the table boundary from the merged title range.
            end_col = 1
            for merged_range in ws.merged_cells.ranges:
                if merged_range.min_row == row and merged_range.max_row == row:
                    end_col = merged_range.max_col
                    break

            table_start = row + 1
            table_end = ws.max_row

            # Stop at the next table title or blank separator after this table.
            for next_row in range(table_start, ws.max_row + 1):
                value = ws.cell(next_row, 1).value
                if (
                    next_row > table_start
                    and isinstance(value, str)
                    and 'UMUR MENGIKUT KAUM DAN JANTINA' in value.upper()
                ):
                    table_end = next_row - 2
                    break

            for r in range(table_start, table_end + 1):
                # Column A contains race/gender labels.
                for c in range(2, end_col + 1):
                    cell = ws.cell(r, c)
                    if not isinstance(cell.value, (int, float)):
                        continue

                    # B, D, F... are counts; C, E, G... are percentages.
                    cell.number_format = '0.0"%"' if c % 2 == 1 else '#,##0'

    output_buffer = io.BytesIO()
    wb.save(output_buffer)
    output_buffer.seek(0)
    return output_buffer.getvalue()


if uploaded_files and age_groups:
    if st.button("Generate DEMOGRAFIK", key="dm_stats_generate_button"):
        try:
            excel_bytes, out_name, logs = dm_stats.generate_demografik(
                uploaded_files,
                age_groups=age_groups
            )

            # Apply final Excel display formatting to both the main table
            # and all DUN age-group/kaum/jantina tables.
            excel_bytes = apply_number_formatting(excel_bytes)

            st.success(f"Generated: {out_name}")

            with st.expander("Processing log"):
                for log in logs:
                    st.write(log)

            st.download_button(
                label="Download Excel",
                data=excel_bytes,
                file_name=out_name,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                key="dm_stats_download_button"
            )

        except Exception as e:
            st.error(str(e))
elif not uploaded_files:
    st.info("Upload one or more Excel files to start.")
